---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  .env.production: |
    NEXT_PUBLIC_ACCOUNTS_BASE_URL=https://accounts.rebrowse.dev
    NEXT_PUBLIC_REBROWSE_API_BASE_URL=https://api.rebrowse.dev
    AUTH_API_BASE_URL=http://auth-api
    SESSION_API_BASE_URL=http://session-api
    BILLING_API_BASE_URL=http://billing-api
    BOOTSTRAP_SCRIPT=https://static.rebrowse.dev/b/development.rebrowse.js
    JAEGER_AGENT_HOST=jaeger-agent.tracing
    JAEGER_AGENT_PORT=6832
