---
apiVersion: v1
kind: ConfigMap
metadata:
  name: try-config
data:
  .env.production: |
    NEXT_PUBLIC_APP_BASE_URL=https://app.rebrowse.dev
    NEXT_PUBLIC_HELP_BASE_URL=https://help.rebrowse.dev
    NEXT_PUBLIC_REBROWSE_API_BASE_URL=https://api.rebrowse.dev
    BOOTSTRAP_SCRIPT=https://static.rebrowse.dev/b/development.rebrowse.js
