---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: session-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - api.rebrowse.dev
      secretName: api-rebrowse-dev-tls
  rules:
    - host: api.rebrowse.dev
      http:
        paths:
          - path: /v1/pages
            backend:
              serviceName: session-api
              servicePort: 80
    - host: api.rebrowse.dev
      http:
        paths:
          - path: /v1/sessions
            backend:
              serviceName: session-api
              servicePort: 80
