on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/frontend:try:storybook.yml'
      - 'frontend/shared/storybook/**'
      - 'frontend/try/**'
      - 'jest.config.js'
      - 'lerna.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'

env:
  CI: true

jobs:
  pr-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: rlespinasse/github-slug-action@master
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install & build üèóÔ∏è
        run: |
          yarn install --frozen-lockfile
          yarn workspace @insight/storybook build
          yarn workspace @insight/try storybook:build
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/try/storybook-static
          TARGET_FOLDER: try:storybook:${{ env.GITHUB_HEAD_REF_SLUG }}
      - name: Comment PR üí¨
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'Storybook preview of frontend/try available at https://meemaw.github.io/Insight/try:storybook:${{ env.GITHUB_HEAD_REF_SLUG }}! üöÄ'
          check_for_duplicate_msg: false
