on:
  push:
    paths:
      - '.github/workflows/frontend:try.yml'
      - 'backend/**'
      - 'frontend/try/**'
      - 'frontend/shared/**'
      - 'jest.config.js'
      - 'lerna.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'

env:
  CI: true
  ARTIFACTS_PATH: frontend/try/artifacts/

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install and unit test
        run: |
          yarn install --frozen-lockfile
          yarn workspace @insight/try test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend:try

  e2e_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: backend | docker-compose up
        run: |
          mkdir -p $ARTIFACTS_PATH
          docker-compose -f backend/local-test-services/docker-compose.yml up auth-api 2>&1 | tee $ARTIFACTS_PATH/docker.log &
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: frontend/try | install
        run: yarn install --frozen-lockfile
      - name: Cache .next/cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/frontend/try/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: frontend/try | build
        run: |
          yarn workspace @insight/testing build
          yarn workspace @insight/try build
      - name: frontend/try | start
        run: |
          yarn workspace @insight/try start 2>&1 | tee $ARTIFACTS_PATH/serve.log &
          node_modules/wait-on/bin/wait-on http-get://localhost:3000 --timeout 60000
          node_modules/wait-on/bin/wait-on http-get://localhost:8080/health/ready --timeout 60000
      - name: frontend/try | test:e2e
        run: |
          mkdir -p $ARTIFACTS_PATH/screenshots
          mkdir -p $ARTIFACTS_PATH/videos
          xvfb-run --server-args="-screen 0 1280x720x24" yarn workspace @insight/try test:e2e
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: artifacts
          path: frontend/try/artifacts
